-- AlterTable
ALTER TABLE "Grid" ADD COLUMN     "name" TEXT,
ADD COLUMN     "payoutFinal" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN     "payoutQ1" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN     "payoutQ2" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN     "payoutQ3" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN     "squarePrice" INTEGER NOT NULL DEFAULT 5;
